do
    KEY_PRESSED_NONE = 0
    KEY_PRESSED_SHIFT = 1
    KEY_PRESSED_CTRL = 2
    KEY_PRESSED_SHIFT_CTRL = 3
    KEY_PRESSED_ALT = 4
    KEY_PRESSED_SHIFT_ALT = 5
    KEY_PRESSED_CTRL_ALT = 6
    KEY_PRESSED_SHIFT_CTRL_ALT = 7
end